spring:
  application:
    name: spring-boot-security

  # datasource details
  datasource:
    url: jdbc:mysql://localhost:3306/sprint_hibernate_course
    username: root
    password: root

# Log JDBC SQL Statements
# Only use this for dev/testing. Should not be used in PRODUCTION
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE

      # add logging configs to display SQL statements and values as well with the help of jdbc bind
      hibernate:
        SQL: debug

